name: Compilar APK Flet

on:
  push:
    branches: [ principal ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar Repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Java (JDK)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Instalar Flet y Dependencias
        run: |
          python -m pip install --upgrade pip
          pip install flet

      - name: Compilar APK de Android
        run: |
          flet build apk PLA_SALIDA_DE_EQUIPOS.py --yes

      - name: Subir APK generado
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: build/apk/app-release.apk
